project/api/urls.py
from django.urls import path
from . import views
app_name = "api"  # Set Namespace for Template using {% url %}
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote', views.vote, name='vote'),
]
# urlpatterns = [
#     path('', views.index, name="index"),
#     path('<int:question_id>/', views.detail, name='detail'),
#     path('<int:question_id>/results', views.results, name='results'),
#     path('<int:question_id>/vote', views.vote, name='vote'),
# ]

project/project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
]

project/api/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.


class Question(models.Model):
    def __str__(self):
        return self.q_text
    q_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date_published')

    def was_published_recently(self):
        return timezone.now() >= self.pub_date \
            >= timezone.now() - datetime.timedelta(days=1)

    # For admin page management of list_display()
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    def __str__(self):
        return self.choice_text
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

project/snippets/models.py
from django.db import models

# Create your models here.

project/api/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Question, Choice
# Create your views here.
# from django.template import loader
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone


# def index(request):
#     # return HttpResponse("Hellio you are inside api app views.py/index")
#     latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     # template = loader.get_template('api/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     # response = template.render(context, request)
#     # response = ", ".join([q.q_text for q in latest_question_list])
#     # return HttpResponse(response)
#     return render(request, 'api/index.html', context)

class IndexView(generic.ListView):
    template_name = "api/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
            ).order_by('-pub_date')[:5]

# def detail(request, question_id):
#     # return HttpResponse("Detail view .. question_id {} "\
#     #                     .format(question_id))
#     try:
#        question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#        raise Http404("Question not found")
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "api/details.html", {'question': question})


class DetailView(generic.DetailView):
    model = Question
    template_name = "api/details.html"


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'api/results.html', {'question': question})
class ResultsView(generic.DetailView):
    model = Question
    template_name = "api/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'api/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('api:results',
                                    args=(question.id,)))

project/api/templates/api/details.html
<!--{{ question }}-->
<h1>{{ question.q_text }}</h1>

{% if error_message %}
<p>
    <strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'api:vote' question.id %}" method="POST">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" 
    value="{{ choice.id }}" />
    <label for="choice {{ forloop.counter }}"> {{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

<br />
<br />

<!--
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>
-->

project/api/templates/api/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'api/style.css' %}" />
{% if latest_question_list %}
    <ul>
    {% for q in latest_question_list %}
<!--        <li><a href="/api/{{ q.id }}/">{{ q.q_text }}</a></li> -->
        <li><a href="{% url 'api:detail' q.id %}">{{ q.q_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p> No Questions are available </p>
{% endif %}

project/api/templates/api/results.html
<h1>{{ question.q_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'api:detail' question.id %}">Vote again?</a>